##AES
##
#' aggregate a pophist object into genetic populations
#' @param ph the output from forward time sim.  includes a pophist object
#' @param gmap data frame that maps forward time populations to genetic populations
#'
#' @return ph list object with new gpophist (genetic pophist) included as a list element
#' @details This function takes a fine-grained spatio-temporal history of a species generated by holoSimCells forward-time simulator and aggregates demographic populations into genetic populations that can be simulated more tractably
#'
#' @export
pophist.aggregate <- function(ph, gmap=NULL)
{
    if (is.null(ph)) stop("must include output from getpophist")
    if (is.null(ph$pophist)) stop("there needs to be a correct pophist in the list 'ph'")
    if (is.null(gmap))
    {
        gh = ph$coalhist
    }    else   { #do the aggregation

        refs <- ph$coalhist[ph$coalhist$time==0,]
        refs$snk <- NA
        refs$prop=1.0
        
        gh <- merge(ph$coalhist,gmap,by.x="src",by.y="pop",all=T)[,1:4]
        names(gh)[4] <- "gsrc"
        gh <- merge(gh,gmap,by.x="snk",by.y="pop")[,1:5]
        names(gh)[5] <- "gsnk"
        gh <- gh[order(gh$time,gh$snk,gh$src),]
        gh$srcsz <- apply(gh[,c("src","time")],1,function(x){ph$Nvec[x[1],paste0("gen",x[2])]})

        agg <- with(gh,aggregate(cbind(mvsrcsz=srcsz),list(time=time,gsnk=gsnk,gsrc=gsrc),sum))
        
        nvt <- aggregate(cbind(ph$Nvecs),list(gpop=gmap$gpop),sum)
        rownames(nvt) <- as.character(nvt$gpop)
        nvt <- nvt[,-1]
        agg$gsrcsz <- apply(agg[,c("gsrc","time")],1,function(x){nvt[x[1],paste0("gen",x[2])]})
        agg$prop <- round(agg$mvsrcsz/agg$gsrcsz,3)
        gh <- agg[agg$gsnk!=agg$gsrc,c("time","gsrc","gsnk","prop")]
        names(gh) <- c("time","src","snk","prop")
        gh <- rbind(refs,gh[order(gh$time,gh$snk,gh$src),])
    }
    ph$coalhist <- gh

    #now the pophist object
    poph <- gmap[,-1]
    names(poph)[1] <- "pop"
    poph <- with(poph,aggregate(cbind(row=row,col=col),list(pop=pop),mean))
    pophist <- merge(ph$pophist,gmap)
    gpophist <- do.call(rbind,lapply(unique(pophist$gpop),function(gp)
    {
        p <- pophist[pophist$gpop==gp,]
#        print(p)
        if (nrow(p)>0)
        {
            ret <- NULL  #data.frame(pop=NA,arrive=NA,source=NA)[-1,]
            for (a in unique(p$arrive))
                for (s in unique(p$source))
                {
                    if (is.na(s)) src <- NA else src <- gmap[gmap$pop==s,"gpop"]
#                    print(paste("gp",gp,"a",a,"s",s,"src",src))

                    if (!is.na(src)[1])
                        if (src!=gp)
                        {
#                            print("adding line")
                            ret <- rbind(ret,
                                         data.frame(pop=gp,arrive=a,source=src))
                        }
                }
            ret
        } else {NULL}
        
    }))
    rc <- with(gmap,aggregate(cbind(row,col),list(pop=gpop),mean))
    gpophist <- merge(gpophist,rc)[,c("pop","col","row","arrive","source")]
###now redo Nvecs
    nv <- aggregate(ph$Nvecs,list(gpop=gmap$gpop),sum)
    rownames(nv) <- as.character(nv$gpop)
    nv <- nv[,-1]
    ph$Nvecs <- nv
###now redo hab_suit (through taking means)
    ph$aggregate_hab_suit <- t(aggregate(t(ph$hab_suit$hab_suit),list(gpop=gmap$gpop),mean))
###now redo tmat
    ysz <- ph$struct["sz"]*length(unique(ph$pophist[ph$pophist$pop %in% gmap[gmap$gpop==1,"pop"],"row"]))
    xsz <- ph$struct["sz"]*length(unique(ph$pophist[ph$pophist$pop %in% gmap[gmap$gpop==1,"pop"],"col"]))
 
    tmat <- integratedMigMat(landx=ceiling(max(gmap$col)/xsz),landy=ceiling(max(gmap$row)/ysz),
                             xnum=5,ynum=5,ysz=ysz,xsz=xsz,
                             sshp=ph$struct["shortshape"],ssc=ph$struct["shortscale"],mix=ph$struct["mix"],
                             nmean=ph$struct["longmean"],nvar=ph$struct["longmean"]^2)
    ph$aggregate_tmat <- tmat
    ph$gmap <- gmap
    ph$pophist <- gpophist
    
    ph
}





#' make a genetic subset map for rectangular landscape
#' @param pophist a demographic population history
#' @param xnum number of columns to aggregate
#' @param ynum number of rows to aggregate
#'
#' @return a gmap object used for pophist.aggregate
#' @details If the size of the landscape in pophist is not evenly divisible by xnum and ynum, "remainder" cells on the top and righthand sides of the landscape will be included in genetic clusters.  As a result the numbers of cells per cluster will vary
#' 
make.gmap <- function(pophist,xnum=2,ynum=2)
{
 ##   remain.right = max(pophist$col) %% xnum
 ##   remain.top = max(pophist$row) %% ynum

    gm=expand.grid(startx=seq(1,max(pophist$col),by=xnum),
                   starty=seq(1,max(pophist$row),by=ynum))
    gm$stopx=lag(gm$startx)+xnum-1
    gm$stopy=lag(gm$starty)+ynum-1
    gm$pop=1:dim(gm)[1]
    gpops=do.call(rbind,lapply(1:dim(gm)[1],function(i) #go through the gpops and find all the pops that fit in each
    {
        tmp = with(pophist,pophist[(col<=gm$stopx[i])&
                                   (col>=gm$startx[i])&
                                   (row<=gm$stopy[i])&
                                   (row>=gm$starty[i]),])
        tmp$gpop=gm$pop[i]
        tmp
    }))
    
    unique(gpops[order(gpops$pop),c("pop","gpop","col","row")])
}


disaggregateLandscape <- function(hs, factor=c(1,2,4,6,8))
{
    old <- hs
    
    
}

