# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

oneMultinomCall <- function(probs) {
    .Call('_holoSimCell_oneMultinomCall', PACKAGE = 'holoSimCell', probs)
}

whichMultinom <- function(probs) {
    .Call('_holoSimCell_whichMultinom', PACKAGE = 'holoSimCell', probs)
}

submat <- function(X, condition) {
    .Call('_holoSimCell_submat', PACKAGE = 'holoSimCell', X, condition)
}

getsrcC <- function(tmat, nv) {
    .Call('_holoSimCell_getsrcC', PACKAGE = 'holoSimCell', tmat, nv)
}

getsrcC2 <- function(tmat, nv) {
    .Call('_holoSimCell_getsrcC2', PACKAGE = 'holoSimCell', tmat, nv)
}

makeRmatC <- function(pops, dm, cent) {
    .Call('_holoSimCell_makeRmatC', PACKAGE = 'holoSimCell', pops, dm, cent)
}

