# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gsl_mult1 <- function(P) {
    .Call(`_holoSimCell_gsl_mult1`, P)
}

oneMultinomCall <- function(probs) {
    .Call(`_holoSimCell_oneMultinomCall`, probs)
}

whichMultinom <- function(probs) {
    .Call(`_holoSimCell_whichMultinom`, probs)
}

submat <- function(X, condition) {
    .Call(`_holoSimCell_submat`, X, condition)
}

getsrcC <- function(tmat, nv) {
    .Call(`_holoSimCell_getsrcC`, tmat, nv)
}

getsrcC2 <- function(tmat, nv) {
    .Call(`_holoSimCell_getsrcC2`, tmat, nv)
}

makeRmatC <- function(pops, dm, cent) {
    .Call(`_holoSimCell_makeRmatC`, pops, dm, cent)
}

rcpp_hello_world <- function() {
    .Call(`_holoSimCell_rcpp_hello_world`)
}

